# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def efib(max=4_000_000):
    first = 1
    second = 2
    while True:
        if second > max:
            return
        elif second & 1 == 0:
            yield second
        third = first + second
        first, second = second, third




res = sum(x for x in efib())
print(res)